### ISSUE TITLE
Clarification on permissions

### ISSUE THREAD

**Issue by upbeatDiamond** [limbusdev/guardian_monsters_artwork#1]
If I redraw the characters, redesigning them on the way, do I have to keep the names the same for English?

As well, what advice do you have on translations of names to other languages, other than trying to preserve the etymology (such as for Toki Pona)?

**Comment by lucidtanooki** [comment]
I already thought about that license part and will remove it. I would prefer if people keep the names but I will not force them anymore.

If you are able to translate, feel free to open up a pull request here. I'll be happy to add it.

**Comment by limbusdev** [comment]
Hope this solves it: https://github.com/limbusdev/guardian_monsters_artwork/blob/master/LICENSE.md

I removed that clause. You are free to rename them. I would be glad if you kept the names but it's not mandatory anymore. 

Translation advice: Keep it simple and easy to pronounce in your language. Keep it nice for everyone.
